// Open a human-reviewed PR on this app's own repo with a proposed prompt revision.
// The revised text is spliced into the source file via exact find/replace (the same
// surgical-edit guarantee used for customer PRs), so only the prompt constant
// changes — the surrounding function code can't be corrupted.

import { githubFetch } from '@/lib/github/client';
import { createPullRequestFromChanges } from '@/lib/github/create-pr';
import type { ImprovablePrompt } from '@/lib/prompts/registry';
import type { AuditEvidence, PromptRevision } from '@/lib/prompts/improve';

interface ContentResponse {
  content: string;
  encoding: string;
  sha: string;
}

/** Make text safe to sit inside a backtick template literal in a .ts source file. */
function escapeForTemplateLiteral(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function buildPrBody(prompt: ImprovablePrompt, revision: PromptRevision, evidence: AuditEvidence): string {
  const gates = Object.entries(evidence.gateFailureRates)
    .map(([k, v]) => `- \`${k}\`: ${(v * 100).toFixed(0)}%`)
    .join('\n');

  return [
    `Automated prompt self-improvement for \`${prompt.exportName}\` (${prompt.filePath}).`,
    '',
    `**Change:** ${revision.changeSummary}`,
    `**Confidence:** ${(revision.confidence * 100).toFixed(0)}%`,
    '',
    '**Rationale**',
    revision.rationale,
    '',
    `**Evidence** — derived from ${evidence.auditsAnalyzed} recent audits.`,
    'Gate failure rates:',
    gates || '- (none)',
    '',
    '⚠️ Generated by the prompt self-improvement loop. Review the wording and the preserved invariants before merging.',
  ].join('\n');
}

export async function openPromptImprovementPr(params: {
  repo: string; // "owner/name"
  defaultBranch?: string;
  prompt: ImprovablePrompt;
  revision: PromptRevision;
  evidence: AuditEvidence;
}): Promise<{ prUrl: string; prNumber: number; branchName: string }> {
  const [owner, repo] = params.repo.split('/');
  if (!owner || !repo) {
    throw new Error('APP_GITHUB_REPO must be in "owner/name" form');
  }
  const defaultBranch = params.defaultBranch ?? 'main';
  const { prompt, revision, evidence } = params;

  const file = await githubFetch<ContentResponse>(
    `/repos/${owner}/${repo}/contents/${prompt.filePath.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(defaultBranch)}`
  );
  const content =
    file.encoding === 'base64' ? Buffer.from(file.content, 'base64').toString('utf-8') : file.content;

  const firstIdx = content.indexOf(prompt.currentText);
  if (firstIdx === -1) {
    throw new Error(
      `Could not locate the current ${prompt.exportName} text in ${prompt.filePath} on ${defaultBranch}; ` +
        'the registry is stale — refresh currentText before retrying.'
    );
  }
  if (content.indexOf(prompt.currentText, firstIdx + 1) !== -1) {
    throw new Error(`${prompt.exportName} text appears more than once in ${prompt.filePath}; aborting to avoid a bad edit`);
  }

  const newContent =
    content.slice(0, firstIdx) +
    escapeForTemplateLiteral(revision.revisedPrompt) +
    content.slice(firstIdx + prompt.currentText.length);

  if (newContent === content) {
    throw new Error('Revised prompt is identical to the current one — nothing to open a PR for');
  }

  return createPullRequestFromChanges({
    owner,
    repo,
    defaultBranch,
    changes: [
      {
        path: prompt.filePath,
        content: newContent,
        message: `Improve ${prompt.exportName} from audit eval feedback`,
      },
    ],
    prTitle: `Prompt self-improvement: ${prompt.label}`,
    prBody: buildPrBody(prompt, revision, evidence),
  });
}
