import { scoreLead } from '@/lib/leads/scoring';
import type { LeadInsert } from '@/lib/leads/types';

export interface LondonSeedLead extends LeadInsert {
  recommendation: string;
}

function buildSeedLead(
  lead: Omit<LondonSeedLead, 'lead_score'>
): LondonSeedLead {
  return {
    ...lead,
    lead_score: scoreLead(lead.rank_position, Boolean(lead.website_url)),
    status: lead.status ?? 'new',
  };
}

export const LONDON_SEED_LEADS: LondonSeedLead[] = [
  buildSeedLead({
    business_name: 'Camden Plumbing Co',
    category: 'plumber',
    location: 'Camden',
    keyword: 'plumber Camden',
    rank_position: 3,
    website_url: 'https://camdenplumbing.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Camden+Plumbing+Co+London',
    phone: '020 7123 4501',
    address: '42 Parkway, Camden Town, London NW1 7AA',
    recommendation:
      'You are one spot from the map pack on "plumber Camden" — rewrite your homepage H1 to lead with "Emergency Plumber in Camden Town" and add LocalBusiness schema with your NW1 postcode. Move your 24/7 call button above the fold on mobile; rank-3 trades lose clicks when the phone number sits below the hero image.',
  }),
  buildSeedLead({
    business_name: 'Hackney Heat & Gas',
    category: 'plumber',
    location: 'Hackney',
    keyword: 'plumber Hackney',
    rank_position: 4,
    website_url: 'https://hackneyheatandgas.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Hackney+Heat+Gas+London',
    phone: '020 7987 2234',
    address: '18 Mare Street, Hackney, London E8 4RH',
    recommendation:
      'At rank 4 you need stronger trust signals — publish a dedicated "Boiler Repair Hackney" landing page and ask your last ten customers for Google reviews mentioning response time. Your meta title should include "Gas Safe" and "Hackney" together; competitors above you likely have more recent review velocity.',
  }),
  buildSeedLead({
    business_name: 'Kensington Pipeworks',
    category: 'plumber',
    location: 'Kensington',
    keyword: 'plumber Kensington',
    rank_position: 3,
    website_url: null,
    phone: '020 7937 8842',
    address: '9 Kensington Church Street, London W8 4LA',
    recommendation:
      'Ranking 3rd without a website is rare but fragile — launch a one-page site with your W8 address, Gas Safe number, and a click-to-call header before a competitor with a proper domain overtakes you. Register on Checkatrade and link back to a simple "Kensington plumber" page to capture the branded searches you are already winning.',
  }),
  buildSeedLead({
    business_name: 'Islington Electric Ltd',
    category: 'electrician',
    location: 'Islington',
    keyword: 'electrician Islington',
    rank_position: 3,
    website_url: 'https://islingtonelectric.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Islington+Electric+London',
    phone: '020 7359 8812',
    address: '7 Upper Street, Islington, London N1 0PQ',
    recommendation:
      'Add an FAQ block answering "How much does an electrician cost in Islington?" — featured snippets often sit above rank 3 and can leapfrog you into position 2. Compress hero images on mobile; your PageSpeed score likely trails NICEIC-listed rivals who load faster on 4G around Upper Street.',
  }),
  buildSeedLead({
    business_name: 'Greenwich Spark Electrical',
    category: 'electrician',
    location: 'Greenwich',
    keyword: 'electrician Greenwich',
    rank_position: 4,
    website_url: 'https://greenwichspark.co.uk',
    phone: '020 8858 3310',
    address: '22 Greenwich High Road, London SE10 8JL',
    recommendation:
      'Create separate service pages for "EV charger installation Greenwich" and "EICR certificates SE10" — you are ranking broadly but missing long-tail intent that pushes electricians from 4 to 2. Add a sticky "Book free quote" bar on mobile; rank-4 listings bleed conversions when users bounce to call the #1 result.',
  }),
  buildSeedLead({
    business_name: 'Clapham Roof Repairs',
    category: 'roofer',
    location: 'Clapham',
    keyword: 'roofer Clapham',
    rank_position: 4,
    website_url: 'https://claphamroofrepairs.co.uk',
    phone: '020 7622 9033',
    address: '88 Clapham High Street, London SW4 7UL',
    recommendation:
      'Upload before/after photos of flat-roof jobs in SW4 with geotagged filenames — Google Images drives a surprising share of roofer leads at rank 4. Rewrite your hero copy to mention "storm damage" and "Clapham" in the first sentence; seasonal urgency helps CRO when you are not yet in the top three.',
  }),
  buildSeedLead({
    business_name: 'Wimbledon Slate & Tile',
    category: 'roofer',
    location: 'Wimbledon',
    keyword: 'roofer Wimbledon',
    rank_position: 3,
    website_url: 'https://wimbledonslateandtile.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Wimbledon+Slate+Tile',
    phone: '020 8946 7710',
    address: '41 Wimbledon Hill Road, London SW19 7NB',
    recommendation:
      'You are close to the map pack — add a prominent "Free roof inspection Wimbledon" CTA above the fold and embed a Google Map on your contact page with driving directions from SW19. Publish a blog post on "Victorian roof repairs in Wimbledon" to capture heritage-home owners who convert at higher ticket sizes.',
  }),
  buildSeedLead({
    business_name: 'City Legal Partners',
    category: 'solicitor',
    location: 'City of London',
    keyword: 'solicitor City of London',
    rank_position: 4,
    website_url: 'https://citylegalpartners.co.uk',
    phone: '020 7248 3300',
    address: '25 Old Broad Street, London EC2N 1HQ',
    recommendation:
      'Professional services at rank 4 need authority content — publish a guide on "Commercial lease disputes in the City" and link it from your homepage. Add attorney schema markup for your lead partners and a consultation booking widget; solicitors lose qualified leads when the only CTA is a generic contact form buried in the footer.',
  }),
  buildSeedLead({
    business_name: 'Westminster Family Law',
    category: 'solicitor',
    location: 'Westminster',
    keyword: 'solicitor Westminster',
    rank_position: 3,
    website_url: null,
    phone: '020 7932 4100',
    address: '3 Dean Bradley Street, Westminster, London SW1P 3HB',
    recommendation:
      'Rank 3 without a site will not hold — build a trust-focused landing page with SRA number, fixed-fee divorce pricing, and client testimonials before Google deprioritises your listing. Even a single-page site with "Family solicitor Westminster" in the title tag would protect the organic position you have earned through directory citations alone.',
  }),
  buildSeedLead({
    business_name: 'Canary Wharf Accounts',
    category: 'accountant',
    location: 'Canary Wharf',
    keyword: 'accountant Canary Wharf',
    rank_position: 3,
    website_url: 'https://cwaccounts.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Canary+Wharf+Accounts',
    phone: '020 7719 5500',
    address: 'One Canada Square, Canary Wharf, London E14 5AB',
    recommendation:
      'Target "contractor accountant Canary Wharf" with a dedicated landing page — your rank-3 position is generic but high-intent niche queries convert better. Add a calendar embed for free 15-minute consultations above the fold; finance leads at position 3 often lose to rivals with instant booking.',
  }),
  buildSeedLead({
    business_name: 'Shoreditch Tax Advisors',
    category: 'accountant',
    location: 'Shoreditch',
    keyword: 'accountant Shoreditch',
    rank_position: 4,
    website_url: 'https://shoreditchtax.co.uk',
    phone: '020 7613 2290',
    address: '45 Charlotte Road, Shoreditch, London EC2A 3PD',
    recommendation:
      'Startup founders search "accountant for startups Shoreditch" — create that page and interlink from your homepage to climb from rank 4. Improve E-E-A-T with ACCA credentials in the header and a client logo strip; creative-industry prospects bounce when the site looks like a template accountancy firm.',
  }),
  buildSeedLead({
    business_name: 'Kensington Property Partners',
    category: 'estate agent',
    location: 'Kensington',
    keyword: 'estate agent Kensington',
    rank_position: 3,
    website_url: 'https://kensingtonpropertypartners.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Kensington+Property+Partners',
    phone: '020 7937 6600',
    address: '112 Kensington Church Street, London W8 4BH',
    recommendation:
      'Add structured data for RealEstateAgent with your W8 office and embed a live property feed on the homepage — rank-3 agents win when listings load without an extra click. Optimise your Google Business Profile with weekly post updates on new instructions; organic rank 3 plus an active GBP often doubles valuation enquiries.',
  }),
  buildSeedLead({
    business_name: 'Clapham Home Sales',
    category: 'estate agent',
    location: 'Clapham',
    keyword: 'estate agent Clapham',
    rank_position: 4,
    website_url: 'https://claphamhomesales.co.uk',
    phone: '020 7622 1188',
    address: '55 Clapham Common South Side, London SW4 9DA',
    recommendation:
      'Publish a "Clapham house price guide 2025" PDF gated behind email capture — rank 4 agents need lead magnets to compete with Foxtons and Kinleigh at positions 1–2. Speed up mobile LCP on property search pages; slow image carousels kill CRO for buyers browsing on the Common commute.',
  }),
  buildSeedLead({
    business_name: 'Soho Kitchen & Co',
    category: 'restaurant',
    location: 'Soho',
    keyword: 'restaurant Soho',
    rank_position: 3,
    website_url: 'https://sohokitchen.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Soho+Kitchen+London',
    phone: '020 7437 9921',
    address: '14 Greek Street, Soho, London W1D 4AL',
    recommendation:
      'Add Restaurant schema with opening hours, menu URL, and acceptsReservations — rank 3 for "restaurant Soho" is crowded and rich results win the click. Put an "Book a table tonight" button in the hero and link OpenTable above the menu PDF; diners at position 3 choose whoever reduces friction fastest.',
  }),
  buildSeedLead({
    business_name: 'Camden Table',
    category: 'restaurant',
    location: 'Camden',
    keyword: 'restaurant Camden',
    rank_position: 4,
    website_url: 'https://camdentable.co.uk',
    phone: '020 7482 3344',
    address: '2 Inverness Street, Camden, London NW1 7HJ',
    recommendation:
      'Optimise for "best brunch Camden" with a dedicated menu page — your rank-4 spot on the head term needs long-tail support. Compress food photography and lazy-load gallery images; restaurant sites in NW1 lose mobile diners when pages take over four seconds on 4G near Camden Market.',
  }),
  buildSeedLead({
    business_name: 'Shoreditch Coffee Lab',
    category: 'cafe',
    location: 'Shoreditch',
    keyword: 'coffee shop Shoreditch',
    rank_position: 4,
    website_url: 'https://shoreditchcoffeelab.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Shoreditch+Coffee+Lab',
    phone: '020 7613 7788',
    address: '91 Redchurch Street, Shoreditch, London E2 7DJ',
    recommendation:
      'Lean into "specialty coffee Shoreditch" in your H1 and add a Google post about your single-origin rotation — cafes at rank 4 rarely win on generic terms alone. Add click-to-directions and opening hours in the sticky mobile header; foot-traffic CRO matters more than blog content for E2 walk-ins.',
  }),
  buildSeedLead({
    business_name: 'Islington Bean Collective',
    category: 'cafe',
    location: 'Islington',
    keyword: 'cafe Islington',
    rank_position: 3,
    website_url: null,
    phone: '020 7354 9021',
    address: '23 Essex Road, Islington, London N1 2SA',
    recommendation:
      'You rank 3rd with only a Google listing — launch a simple one-page site with your menu, vegan options, and N1 address before a rival café with a blog overtakes you. Enable online ordering via Square or similar and link it from your GBP; rank-3 cafés without web ordering leak lunch orders to Deliveroo-listed competitors.',
  }),
  buildSeedLead({
    business_name: 'The George & Dragon',
    category: 'pub',
    location: 'Greenwich',
    keyword: 'pub Greenwich',
    rank_position: 3,
    website_url: 'https://georgeanddragongreenwich.co.uk',
    phone: '020 8858 4400',
    address: '151 Greenwich High Road, London SE10 8JA',
    recommendation:
      'Add Event schema for quiz nights and live sport — pubs at rank 3 in Greenwich compete with chains that dominate rich results. Feature your beer garden and Sunday roast in the hero with a "View menu" CTA above the fold; weekend CRO jumps when food menus are one tap away on mobile.',
  }),
  buildSeedLead({
    business_name: 'The Clapham Arms',
    category: 'pub',
    location: 'Clapham',
    keyword: 'pub Clapham',
    rank_position: 4,
    website_url: 'https://claphamarms.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Clapham+Arms+London',
    phone: '020 7627 2210',
    address: '16 Clapham Common South Side, London SW4 7AB',
    recommendation:
      'Build a "Private hire Clapham" page — event revenue matters more than organic pub searches and supports your climb from rank 4. Refresh your Google photos with recent interior shots; stale GBP galleries push drinkers toward the polished listings holding positions 1 and 2 on the Common.',
  }),
  buildSeedLead({
    business_name: 'Clapham Dental Studio',
    category: 'dentist',
    location: 'Clapham',
    keyword: 'dentist Clapham',
    rank_position: 4,
    website_url: 'https://claphamdentalstudio.co.uk',
    phone: '020 7622 4410',
    address: '62 Clapham High Street, London SW4 7UL',
    recommendation:
      'Create a "Invisalign Clapham" service page with pricing ranges — dental rank 4 is often a single treatment page away from rank 2. Add a prominent "New patient offer" banner and NHS/private clarity in the first screen; dental CRO fails when insurance acceptance is buried below the team bios.',
  }),
  buildSeedLead({
    business_name: 'Shoreditch Smile Clinic',
    category: 'dentist',
    location: 'Shoreditch',
    keyword: 'dentist Shoreditch',
    rank_position: 3,
    website_url: 'https://shoreditchsmile.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Shoreditch+Smile+Clinic',
    phone: '020 7613 5500',
    address: '12 Paul Street, Shoreditch, London EC2A 4NE',
    recommendation:
      'You are one push from the map pack — add Dentist schema, aggregate your 4.8★ reviews on the homepage, and implement online booking in the header. Rank-3 dental practices in EC2 convert when "Book hygienist appointment" is visible without scrolling on iPhone screens.',
  }),
  buildSeedLead({
    business_name: 'Westminster Vision Centre',
    category: 'optician',
    location: 'Westminster',
    keyword: 'optician Westminster',
    rank_position: 4,
    website_url: 'https://westminstervision.co.uk',
    phone: '020 7930 8811',
    address: '40 Victoria Street, Westminster, London SW1H 0NB',
    recommendation:
      'Add a "Designer frames Westminster" collection page with brand filters — opticians at rank 4 need product-led SEO, not just service copy. Offer a free eye test CTA with online slot booking; SW1 shoppers compare three sites before visiting and you lose when Specsavers is easier to book.',
  }),
  buildSeedLead({
    business_name: 'Wimbledon Physio Care',
    category: 'physio',
    location: 'Wimbledon',
    keyword: 'physio Wimbledon',
    rank_position: 3,
    website_url: 'https://wimbledonphysio.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Wimbledon+Physio+Care',
    phone: '020 8946 1155',
    address: '33 Wimbledon Hill Road, London SW19 7NB',
    recommendation:
      'Publish condition-specific pages for "sports physio Wimbledon" and "post-surgery rehab SW19" — your rank-3 generic listing should fan out into high-intent clusters. Add practitioner schema with HCPC numbers and a "Same-week appointments" badge in the hero to improve trust-led CRO.',
  }),
  buildSeedLead({
    business_name: 'Hackney Movement Physio',
    category: 'physio',
    location: 'Hackney',
    keyword: 'physio Hackney',
    rank_position: 4,
    website_url: null,
    phone: '020 8985 3320',
    address: '4 Broadway Market, Hackney, London E8 4QJ',
    recommendation:
      'Rank 4 without a website is unsustainable in Hackney\'s competitive health market — stand up a site with your E8 address, treatment list, and Physiotherapist schema this week. Link from your Instagram bio and GBP to capture the branded searches you are already getting from Broadway Market foot traffic.',
  }),
  buildSeedLead({
    business_name: 'Camden Fit House',
    category: 'gym',
    location: 'Camden',
    keyword: 'gym Camden',
    rank_position: 4,
    website_url: 'https://camdenfithouse.co.uk',
    phone: '020 7485 6600',
    address: '12 Kentish Town Road, Camden, London NW1 8NH',
    recommendation:
      'Launch a "Free trial day Camden" landing page with a form above the fold — gyms at rank 4 must optimise for trial sign-ups, not vanity traffic. Add FAQ schema on membership pricing and freeze policies; comparison shoppers bounce when prices require a phone call.',
  }),
  buildSeedLead({
    business_name: 'Canary Wharf Fitness Club',
    category: 'gym',
    location: 'Canary Wharf',
    keyword: 'gym Canary Wharf',
    rank_position: 3,
    website_url: 'https://cwfitnessclub.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Canary+Wharf+Fitness+Club',
    phone: '020 7719 8800',
    address: '25 Bank Street, Canary Wharf, London E14 5JP',
    recommendation:
      'Target "office gym Canary Wharf" and "before-work classes E14" — rank 3 on the broad term is valuable but niche pages drive corporate memberships. Show class timetables without login and add a corporate enquiry CTA; City workers convert when they can scan 6am slots in under ten seconds.',
  }),
  buildSeedLead({
    business_name: 'Soho Skin Studio',
    category: 'beauty',
    location: 'Soho',
    keyword: 'beauty salon Soho',
    rank_position: 3,
    website_url: 'https://sohoskinstudio.co.uk',
    phone: '020 7437 2200',
    address: '8 Berwick Street, Soho, London W1F 0PH',
    recommendation:
      'Add Fresha or Treatwell booking embed above your service menu — beauty rank 3 in W1 is won on booking friction, not SEO alone. Create individual pages for "Hydrafacial Soho" and "Brow lamination Berwick Street" to capture treatment-specific searches that convert at 3× the generic salon query.',
  }),
  buildSeedLead({
    business_name: 'Kensington Auto Care',
    category: 'auto',
    location: 'Kensington',
    keyword: 'car service Kensington',
    rank_position: 4,
    website_url: 'https://kensingtonautocare.co.uk',
    google_maps_url: 'https://maps.google.com/?q=Kensington+Auto+Care',
    phone: '020 7937 5500',
    address: '67 Warwick Road, Kensington, London SW5 9HB',
    recommendation:
      'Publish transparent MOT and service pricing tables — auto shops at rank 4 lose to Kwik Fit on trust unless prices are visible upfront. Add LocalBusiness schema with opening hours and a "Book MOT online" CTA; SW5 drivers compare three garages before calling and you need to be the easiest to book.',
  }),
  buildSeedLead({
    business_name: 'Islington Clean Team',
    category: 'cleaning',
    location: 'Islington',
    keyword: 'cleaning service Islington',
    rank_position: 4,
    website_url: 'https://islingtoncleanteam.co.uk',
    phone: '020 7354 7700',
    address: '14 Barnsbury Road, Islington, London N1 0PN',
    recommendation:
      'Build a "End of tenancy cleaning Islington" page with a fixed-price calculator — cleaning at rank 4 needs productised offers, not vague "contact us" copy. Collect and display Google reviews mentioning reliability and N1 postcodes; domestic services climb when social proof matches the neighbourhood searched.',
  }),
  buildSeedLead({
    business_name: 'Greenwich Tutors Collective',
    category: 'tutoring',
    location: 'Greenwich',
    keyword: 'tutor Greenwich',
    rank_position: 3,
    website_url: 'https://greenwichtutors.co.uk',
    phone: '020 8858 9900',
    address: '5 Royal Hill, Greenwich, London SE10 8RR',
    recommendation:
      'Add separate GCSE and A-Level landing pages with tutor credentials and SE10 availability — rank 3 for "tutor Greenwich" is broad but parents search by exam level. Place a "Free 20-minute assessment" CTA in the hero; tutoring CRO hinges on low-commitment first steps before term-fee conversations.',
  }),
];
